repos:
- repo: local
  hooks:
  - id: go-build
    name: go build
    language: system
    entry: go build -v ./...
    pass_filenames: false
    types: [go]

  - id: golangci-lint
    name: golangci-lint
    language: system
    entry: golangci-lint run
    pass_filenames: false
    types: [go]

  - id: task-generate
    name: task generate
    language: system
    entry: bash -c 'task generate && git diff --compact-summary --exit-code || (echo; echo "Unexpected difference after task generate. Commit the generated files."; exit 1)'
    pass_filenames: false
    stages: [pre-commit]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: check-yaml
    args: ['--unsafe']
  - id: detect-private-key
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude: ^docs/
  - id: check-json
  - id: pretty-format-json
    args:
    - --autofix
    - --no-ensure-ascii
    - --no-sort-keys

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.30
  hooks:
  - id: tflint
    args:
    - --recursive
    - --disable-rule=terraform_unused_declarations
    - --disable-rule=terraform_required_version
    - --disable-rule=terraform_required_providers

- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.18
  hooks:
  - id: shellcheck
